### PR TITLE
Introduce different `sub-module-mode` configuration options

### PR DESCRIPTION
**Pull request by mikepenz**
- introduce new configuration for different `sub-module-mode`s
  - FIX https://github.com/mikepenz/gradle-dependency-submission/issues/72
- introduce new testcases to test different sub module modes (`INDIVIDUAL`, `COMBINED`, `IGNORE`)

### CODE REVIEW

**Comment by agonzalez-plume** [comment]
Ran this update using 'INDIVIDUAL option, got the following error.. Guess we need to go to 7.5.0, will need to research that

'''
Warning: The current gradle version does not support retrieving a single property. Found version: 7.4.2. At least required: 7.5.0
Error: 🚨 Could not retrieve the gradle dependency path (to the build.gradle) for :residential-ui

/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.7.0/webpack:/gradle-dependency-submission/lib/process.js:28
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
^
Error: Failed to retrieve gradle build path.
    at /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.7.0/webpack:/gradle-dependency-submission/lib/process.js:53:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.7.0/webpack:/gradle-dependency-submission/lib/process.js:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
'''

**Comment by mikepenz** [comment]
@agonzalez-plume Thank you for the report. 

Yes that's correct. Gradle 7.5 introduces the ability to retrieve a single property from a project. 
While I could achieve compatibility with 7.4 by retrieving all properties, we decided to lower the scope and be as restrictive as possible. (as such only reading particular properties required) - You can audit this here: https://github.com/mikepenz/gradle-dependency-submission/blob/main/src/gradle.ts#L88-L107

While it requires Gradle 7.5. It does not require your gradle wrapper to be that version. 

If you have Gradle 7.5 installed on the runner, you can use `gradle` (e.g. `use-gradlew=false`) instead

**Comment by agonzalez-plume** [comment]
I see, didn't realize it was your code spitting that msg out. question, for my knowledge... I see mention about snapshots going to the commit, but in a test I did on a branch of a repo, the snapshot got created and submitted successfully and ended up going in the ether. Do the submissions only work on the default_branch? Like if the PR is merged? I can test some more, though the repo I'm testing on is not ideal to do the merge and see.

**Comment by mikepenz** [comment]
@agonzalez-plume the idea of this action is to rely on `Gradle` without the need to apply a plugin, or the need for the action to inject custom plugins into `Gradle` - solely rely on existing APIs. 

As such this action uses and relies on:
```
gradle {moduleName}:dependencies --configuration {configuration}
```
and
```
gradle {moduleName}:properties --property buildFile
```
and 
```
gradle :properties --property name
```
-----

regarding your second question. Yes the submission only works on the `default_branch` this seems to be a GitHub requirement. 
Screen Shot 2022-08-23 at 08 51 09


There seems to sadly be no documentation or description in the docs though: https://docs.github.com/en/rest/dependency-graph/dependency-submission

The action passes the `ref` on where the submission was done from, maybe GitHub will offer to configure the branch in the future, but for now only default branch works.

**Comment by agonzalez-plume** [comment]
Yes, I agree using the normal gradle dependencies command is ideal. This action works really well in that I could configure the settings just the way our complicated build process needs it.

And thanks for pointing out that screenshot, I went back and looked around and couldn't find the snippet where Github said it required default branch. I thought I saw it, but couldn't find it, apparently because it was in your README!

**Pull request merged**
